import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GoogleAnalytics } from '@next/third-parties/google'
import { ClerkProvider } from '@clerk/nextjs'; // ✅ 添加 ClerkProvider
import "../styles/index.css";
import '../styles/globals.css';


// todo: complete google analytics
// https://nextjs.org/docs/messages/next-script-for-ga

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={inter.className}>
            {children}
            </body>
            <GoogleAnalytics gaId="G-XYZ" />
            </html>
        </ClerkProvider>
    );
}