-- Update Users table
ALTER TABLE users
  DROP COLUMN IF EXISTS password_hash,
  ADD COLUMN IF NOT EXISTS github VARCHAR,
  ADD COLUMN IF NOT EXISTS linkedin VARCHAR,
  ADD COLUMN IF NOT EXISTS resume VARCHAR;

-- Update Mentors table
ALTER TABLE mentors
  DROP COLUMN IF EXISTS role,
  DROP COLUMN IF EXISTS industry,
  ADD COLUMN IF NOT EXISTS title VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS company VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS years_of_experience INTEGER NOT NULL,
  ADD COLUMN IF NOT EXISTS years_of_experience_recorded_date TIMESTAMP WITH TIME ZONE NOT NULL,
  ADD COLUMN IF NOT EXISTS introduction TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS industries VARCHAR[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS services JSONB NOT NULL DEFAULT '{}';

-- Add any missing timestamps
ALTER TABLE mentors
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;